buildFuture = true
baseURL = "https://sinoqueerse.org/"
languageCode = "zh-cn"
title = "北方酷儿 Sino-Queer Sweden"
theme = "ananke"

[params]
  # 站点描述（SEO）
  description = """我们是北方酷儿，一个诞生在瑞典的华语酷儿(LGBTQ+)和女性主义社群，希望为身在瑞典的离散华语酷儿/女权伙伴提供安全、多元、包容的表达空间和社群支持，以交叉性视角关注女性和性少数权益。
                We are Sino-Queer Sweden, a Chinese-speaking LGBTQ+ and feminist community based in Sweden. We aim to connect, support and empower queer/feminist diasporas by building safe spaces and initiating dialogues."""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 20
  [[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 30